### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by DiscordT00ls** [hoemotion/Karuma#14] opened 2022-11-09 16:34 UTC
Client.start() got an unexpected keyword argument 'bot'

**Comment by hoemotion** [comment] 2022-11-09 18:00
Do you have discord.py version 1.7.3 installed? This might be a duplicate of [ Issue 12 ](https://github.com/hoemotion/Karuma/issues/12)

**Closed by hoemotion** 2022-11-09 18:00 UTC
